#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1

putfile() {
             print $1
             aws --profile AWS s3                   cp ./$1 s3://www.awslearningresources.com/$1 --acl public-read
             return true;
}

putfile mycheatsheet.html
putfile vimcheatsheet.html
putfile cheatsheet.css
