#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1


cd ..
punch plugin
cd plugin

git clone git@github.com:archernar/polymode.vim.git /tmp/repotemp

ls -lh /tmp/repotemp

rm -rf /home/mestes/.vim/bundle/polymode.vim
cp -r /tmp/repotemp/* /home/mestes/.vim/bundle/polymode.vim/

ls -lh /home/mestes/.vim/bundle/polymode.vim


rm -rf /tmp/repotemp
