#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1


while getopts "rls" arg
do
	case $arg in
            r) 
               cd ..
               punch plugin
               cd plugin
               git clone git@github.com:archernar/polymode.vim.git /tmp/repotemp
               ls -lh /tmp/repotemp
               rm -rf ~/.vim/bundle/polymode.vim
               mkdir ~/.vim/bundle/polymode.vim
               cp -r /tmp/repotemp/* ~/.vim/bundle/polymode.vim/
               ls -lh ~/.vim/bundle/polymode.vim
               rm -rf /tmp/repotemp
               exit 0
               ;;
            l) 
               print "local deploy"
               cp polymode.vim ~/.vim/bundle/polymode.vim/plugin/polymode.vim
               exit 0
               ;;
            s) 
               print "cp polymode.safe"
               cp  ~/.vim/bundle/polymode.vim/plugin/polymode.vim /tmp/polymode.old.safe
               cp polymode.safe ~/.vim/bundle/polymode.vim/plugin/polymode.vim
               exit 0
               ;;
	    *) print " -r for remote"
	       print " -l for local"
	       print " -s for safe store"
               exit 0 
               ;;
	esac
done
shift $(($OPTIND - 1))


